### ISSUE TITLE
Add script to load the machine

### ISSUE THREAD

**Issue by viveksahu26** [saiyam1814/PCA#1]
I was practicing this. One thing atm, missing was that prometheus graph doesnot seems to variate alot. Due to which could not get feel  of it. So, to variate the graph, continous changes in the resource to be occur. To do so add  load on the machine which will reflects to the variation in the graph.

We can add small script to add load on the machine.

**Comment by saiyam1814** [comment]
Sure , can you raise a PR for this ?
